def get_training_data():
    return [

        # Money / Cash / Prize scams
        ("Win free cash now", "spam"),
        ("Get a free gift waiting for you", "spam"),
        ("Click here for free money", "spam"),
        ("Congratulations! You won the lottery", "spam"),
        ("Claim your $1000 Walmart gift card!", "spam"),
        ("You have been selected for a special exclusive offer", "spam"),
        ("Earn money working from home easy", "spam"),
        ("Limited time offer: get 50% off all purchases", "spam"),
        ("You won a million dollars claim now", "spam"),
        ("Free cash giveaway click the link", "spam"),
        ("Collect your prize money today", "spam"),
        ("You are our lucky winner of $5000", "spam"),
        ("Get paid $500 daily doing nothing", "spam"),
        ("Instant cash transfer to your account", "spam"),
        ("Win big with our online casino", "spam"),
        ("Double your income in just one week", "spam"),
        ("Earn $1000 per day from home", "spam"),
        ("Free money no strings attached", "spam"),
        ("You have won a brand new car", "spam"),
        ("Claim your free vacation package now", "spam"),

        # Product / Shopping scams
        ("Buy our product now cheap", "spam"),
        ("Huge discount on all electronics today only", "spam"),
        ("Buy one get one free limited time", "spam"),
        ("Exclusive deal just for you act now", "spam"),
        ("Flash sale everything must go today", "spam"),
        ("Save 90% on designer watches", "spam"),
        ("Cheap medications delivered to your door", "spam"),
        ("Order now and get free shipping worldwide", "spam"),
        ("Best prices guaranteed on all products", "spam"),
        ("Unbeatable prices on brand name items", "spam"),
        ("Wholesale prices for retail customers", "spam"),
        ("Clearance sale up to 80% off everything", "spam"),
        ("Premium products at rock bottom prices", "spam"),
        ("Get the best deal on insurance today", "spam"),
        ("Amazing deals on luxury items click here", "spam"),
        ("Shop now and save big on everything", "spam"),
        ("Discount code inside open now", "spam"),
        ("Massive savings on your favorite brands", "spam"),
        ("Today only free gift with every purchase", "spam"),
        ("Lowest prices of the year don't miss out", "spam"),

        # Urgency / Account scams
        ("Urgent: Your account has been compromised, click here to verify", "spam"),
        ("Your account will be closed if you don't respond", "spam"),
        ("Immediate action required on your account", "spam"),
        ("Your password has expired click here to reset", "spam"),
        ("Verify your identity now or lose access", "spam"),
        ("Suspicious activity detected on your account", "spam"),
        ("Your bank account has been locked", "spam"),
        ("Update your payment information immediately", "spam"),
        ("Security alert: unauthorized login attempt detected", "spam"),
        ("Confirm your account details to avoid suspension", "spam"),
        ("Your account needs verification click below", "spam"),
        ("Warning: your credit card has been charged", "spam"),
        ("Action required: update your billing details now", "spam"),
        ("Your subscription is about to expire renew now", "spam"),
        ("Final warning: your account will be terminated", "spam"),
        ("Unusual sign in activity on your account", "spam"),
        ("Complete verification to restore your account", "spam"),
        ("Your recent transaction needs confirmation", "spam"),
        ("Important security update for your account", "spam"),
        ("We detected a problem with your payment method", "spam"),

        # Loan / Finance scams
        ("Get a personal loan with zero interest", "spam"),
        ("Pre-approved loan offer just for you", "spam"),
        ("Bad credit? No problem get approved today", "spam"),
        ("Low interest rate loans available now", "spam"),
        ("Consolidate your debt with one easy payment", "spam"),
        ("Get approved for a mortgage in minutes", "spam"),
        ("Financial freedom is just one click away", "spam"),
        ("Invest now and watch your money grow", "spam"),
        ("Double your investment guaranteed returns", "spam"),
        ("Make money with cryptocurrency trading", "spam"),
        ("Secret investment strategy revealed", "spam"),
        ("Get rich quick with this simple trick", "spam"),
        ("Retire early with our investment plan", "spam"),
        ("Guaranteed returns on your investment", "spam"),
        ("Exclusive investment opportunity limited spots", "spam"),
        ("Trade stocks from home and earn daily profits", "spam"),
        ("Your credit score qualifies you for a special offer", "spam"),
        ("Apply now for a no fee credit card", "spam"),
        ("Unlock your financial potential today", "spam"),
        ("Free financial consultation call now", "spam"),

        # Health / Weight loss scams
        ("Lose weight fast with this miracle pill", "spam"),
        ("Amazing weight loss results guaranteed", "spam"),
        ("Burn fat while you sleep", "spam"),
        ("Natural supplement cures all diseases", "spam"),
        ("Doctors don't want you to know this secret", "spam"),
        ("Revolutionary health breakthrough", "spam"),
        ("Get fit in just 7 days", "spam"),
        ("Anti-aging cream makes you look 20 years younger", "spam"),
        ("Boost your energy with this natural remedy", "spam"),
        ("Secret diet pill celebrities use", "spam"),
        ("Lose 30 pounds in 30 days guaranteed", "spam"),
        ("This superfood will change your life", "spam"),
        ("Order prescription drugs online no prescription needed", "spam"),
        ("Free trial of our weight loss supplement", "spam"),
        ("Look younger with our skincare formula", "spam"),
        ("Increase your stamina with this one trick", "spam"),
        ("Natural cure for diabetes discovered", "spam"),
        ("Eliminate wrinkles overnight guaranteed", "spam"),
        ("The health secret big pharma hides from you", "spam"),
        ("Miracle supplement boosts immunity instantly", "spam"),

        # Dating / Adult scams
        ("Hot singles in your area want to meet you", "spam"),
        ("Find your perfect match today", "spam"),
        ("Lonely? Meet attractive people near you", "spam"),
        ("Someone has a crush on you find out who", "spam"),
        ("Beautiful women are waiting for you online", "spam"),
        ("Join our exclusive dating site free", "spam"),
        ("Meet local singles tonight no signup", "spam"),
        ("Your secret admirer wants to connect", "spam"),
        ("Start dating beautiful people today", "spam"),
        ("Attractive singles are looking for you", "spam"),

        # Work from home / Job scams
        ("Work from home and earn thousands", "spam"),
        ("Hiring now no experience needed", "spam"),
        ("Be your own boss start today", "spam"),
        ("Make money online with no investment", "spam"),
        ("Data entry jobs earn $50 per hour", "spam"),
        ("Start your own business with zero capital", "spam"),
        ("Part time work full time pay", "spam"),
        ("Remote job opportunity high salary apply now", "spam"),
        ("Join our team and earn passive income", "spam"),
        ("Quit your job and work from anywhere", "spam"),
        ("Flexible hours high pay work from home", "spam"),
        ("Simple online tasks pay up to $200 daily", "spam"),
        ("Turn your spare time into cash", "spam"),
        ("Get paid to take online surveys", "spam"),
        ("Become a millionaire with our business model", "spam"),

        # Generic spam / Phishing
        ("Click here to claim your reward", "spam"),
        ("You have a package waiting click to track", "spam"),
        ("Open this attachment for important info", "spam"),
        ("Forward this to 10 friends and win a prize", "spam"),
        ("This is not a scam click to learn more", "spam"),
        ("Act now before this offer expires", "spam"),
        ("Don't miss this once in a lifetime opportunity", "spam"),
        ("Reply with your personal details to proceed", "spam"),
        ("Congratulations you have been chosen", "spam"),
        ("You are eligible for a government grant", "spam"),
        ("Free iPhone giveaway enter now", "spam"),
        ("Download this app and earn rewards", "spam"),
        ("Your email has been selected for a reward", "spam"),
        ("Activate your complimentary membership now", "spam"),
        ("Special promotion for loyal customers only", "spam"),
        ("Dear customer your refund is ready", "spam"),
        ("Complete this survey for a free gift card", "spam"),
        ("Unlock exclusive content by clicking here", "spam"),
        ("Hurry limited stock available order now", "spam"),
        ("Your entry has been confirmed in our sweepstakes", "spam"),
        ("Register now for a chance to win big prizes", "spam"),
        ("We need your help transferring funds", "spam"),
        ("Inheritance money waiting for you overseas", "spam"),
        ("Please provide bank details for wire transfer", "spam"),
        ("Prince from Nigeria wants to share wealth", "spam"),
        ("You have unclaimed insurance benefits", "spam"),
        ("IRS refund notification claim your money", "spam"),
        ("Congratulations on your tax refund click here", "spam"),
        ("You qualify for a government stimulus payment", "spam"),
        ("Your delivery could not be completed click to reschedule", "spam"),

        # Software / Tech scams
        ("Your computer has a virus download antivirus now", "spam"),
        ("Speed up your PC with this free tool", "spam"),
        ("Free software download no registration required", "spam"),
        ("Your device is infected click here to clean", "spam"),
        ("Upgrade your storage for free limited time", "spam"),
        ("VPN service lifetime subscription for $10", "spam"),
        ("Get premium software for free", "spam"),
        ("Protect your privacy install this app now", "spam"),
        ("Free cloud storage upgrade click here", "spam"),
        ("Remove all malware with one click download now", "spam"),

        # ===== HAM EXAMPLES (200) =====

        # Greetings / Casual
        ("Hello friend how are you", "ham"),
        ("Hey what's up long time no see", "ham"),
        ("Good morning hope you have a great day", "ham"),
        ("Hi there just wanted to say hello", "ham"),
        ("How have you been lately", "ham"),
        ("Hope you are doing well", "ham"),
        ("Happy birthday to you have a wonderful day", "ham"),
        ("Wishing you a happy anniversary", "ham"),
        ("Thanks for everything you do", "ham"),
        ("It was great seeing you yesterday", "ham"),
        ("Take care and talk soon", "ham"),
        ("Have a safe trip see you when you get back", "ham"),
        ("Congratulations on your new job", "ham"),
        ("Good luck on your exam tomorrow", "ham"),
        ("Thinking of you hope things are going well", "ham"),

        # Work / Office
        ("Meeting at 10 am tomorrow", "ham"),
        ("Can you send the report", "ham"),
        ("Are we still on for the meeting?", "ham"),
        ("Here is the requested document for review", "ham"),
        ("The project deadline has been extended to Friday", "ham"),
        ("Please review the attached proposal", "ham"),
        ("Can we reschedule our call to 3 pm", "ham"),
        ("The client approved the design mockups", "ham"),
        ("I'll send the updated spreadsheet by end of day", "ham"),
        ("Let's discuss the quarterly results tomorrow", "ham"),
        ("Team standup meeting moved to 11 am", "ham"),
        ("Please update the project timeline", "ham"),
        ("The new hire starts on Monday", "ham"),
        ("Can you cover my shift on Thursday", "ham"),
        ("HR needs your updated contact information", "ham"),
        ("The conference room is booked for our presentation", "ham"),
        ("I finished the code review for the feature branch", "ham"),
        ("The deployment went smoothly last night", "ham"),
        ("Let me know if you need help with the documentation", "ham"),
        ("We need to submit the report by end of week", "ham"),
        ("The budget has been approved for next quarter", "ham"),
        ("Management wants an update on project status", "ham"),
        ("I've shared the meeting notes with the team", "ham"),
        ("Can you send me the latest version of the slides", "ham"),
        ("The training session is scheduled for next Wednesday", "ham"),
        ("Please fill out the performance review form", "ham"),
        ("I'm working from home today", "ham"),
        ("The office will be closed on public holiday", "ham"),
        ("We have a new intern starting next week", "ham"),
        ("The printer on the second floor is not working", "ham"),

        # Social / Plans
        ("Let's grab lunch today", "ham"),
        ("Did you watch the game last night?", "ham"),
        ("Let me know when you are available for a quick chat", "ham"),
        ("Don't forget to pick up groceries", "ham"),
        ("Are you coming to the party this weekend", "ham"),
        ("Let's plan a trip for the long weekend", "ham"),
        ("Want to go see a movie tonight", "ham"),
        ("I'll pick you up at 7 pm", "ham"),
        ("Dinner is at my place Saturday evening", "ham"),
        ("We should catch up over coffee sometime", "ham"),
        ("Are you free this Saturday for a hike", "ham"),
        ("Let's try that new restaurant downtown", "ham"),
        ("Game night at my apartment this Friday", "ham"),
        ("Do you want to go shopping tomorrow", "ham"),
        ("Book club meeting is at 6 pm on Thursday", "ham"),
        ("I'm thinking of hosting a barbecue this weekend", "ham"),
        ("Shall we go for a walk after work", "ham"),
        ("Want to join us for bowling on Friday night", "ham"),
        ("The concert tickets are selling fast should I buy", "ham"),
        ("Let's meet at the park this afternoon", "ham"),

        # Family / Personal
        ("Mom said to call her when you get a chance", "ham"),
        ("Don't forget Dad's birthday is next Tuesday", "ham"),
        ("The kids have a school play on Wednesday", "ham"),
        ("Can you pick up the kids from school today", "ham"),
        ("Grandma is visiting us this weekend", "ham"),
        ("Family dinner at 7 pm don't be late", "ham"),
        ("Your sister called she wants to talk to you", "ham"),
        ("We need to buy a gift for the baby shower", "ham"),
        ("The dog needs to go to the vet tomorrow", "ham"),
        ("I scheduled the plumber for Tuesday morning", "ham"),
        ("Remember to water the plants while I'm away", "ham"),
        ("The landlord is coming for inspection on Friday", "ham"),
        ("We need to renew the car insurance this month", "ham"),
        ("The electricity bill is due next week", "ham"),
        ("Can you pick up milk on your way home", "ham"),
        ("I left my keys on the kitchen counter", "ham"),
        ("Our flight is at 6 am don't forget to set alarm", "ham"),
        ("The package was delivered and left at the door", "ham"),
        ("We need to schedule the annual checkup", "ham"),
        ("The car needs an oil change soon", "ham"),

        # School / Study
        ("The assignment is due on Monday", "ham"),
        ("I need help with the math homework", "ham"),
        ("Professor canceled class tomorrow", "ham"),
        ("Study group meeting at the library at 4 pm", "ham"),
        ("Can I borrow your notes from yesterday's lecture", "ham"),
        ("The exam results will be posted on Friday", "ham"),
        ("I submitted the project report yesterday", "ham"),
        ("Don't forget to bring your textbook to class", "ham"),
        ("The lab session has been moved to room 302", "ham"),
        ("Registration for next semester starts Monday", "ham"),
        ("I got an A on my midterm exam", "ham"),
        ("The thesis submission deadline is next month", "ham"),
        ("Can we practice the presentation together", "ham"),
        ("The seminar on machine learning is at 2 pm", "ham"),
        ("I need to return these library books before Friday", "ham"),
        ("The professor posted new reading materials online", "ham"),
        ("Our group project meeting is after lunch", "ham"),
        ("Have you started studying for the finals yet", "ham"),
        ("The scholarship application deadline is approaching", "ham"),
        ("Class will be held online next week", "ham"),

        # Technology / Help
        ("Can you help me set up the new laptop", "ham"),
        ("The wifi password has been changed", "ham"),
        ("I updated the software on your computer", "ham"),
        ("The website is down for maintenance", "ham"),
        ("Please save your work before restarting", "ham"),
        ("The backup completed successfully", "ham"),
        ("Can you share the google drive folder link", "ham"),
        ("I sent you the files via email", "ham"),
        ("The app needs an update to work properly", "ham"),
        ("Let me know if you're having trouble logging in", "ham"),
        ("I created a shared folder for our documents", "ham"),
        ("The new software version fixes the bug we found", "ham"),
        ("Can you test the application on your phone", "ham"),
        ("I pushed the changes to the main branch", "ham"),
        ("The database migration ran without any errors", "ham"),

        # Health / Wellbeing
        ("Remember to take your medicine after dinner", "ham"),
        ("The doctor's appointment is at 3 pm tomorrow", "ham"),
        ("I signed us up for the gym membership", "ham"),
        ("Let's start going for morning walks", "ham"),
        ("Drink more water it's really hot today", "ham"),
        ("I'm feeling much better today thanks for asking", "ham"),
        ("The dentist appointment has been rescheduled", "ham"),
        ("Can you bring me some soup I'm not feeling well", "ham"),
        ("Get some rest and feel better soon", "ham"),
        ("The pharmacy called your prescription is ready", "ham"),

        # Food / Cooking
        ("What do you want for dinner tonight", "ham"),
        ("I made pasta for lunch it's on the stove", "ham"),
        ("Can you pick up some vegetables from the store", "ham"),
        ("The new cafe on Main Street has great coffee", "ham"),
        ("I found a good recipe for chocolate cake", "ham"),
        ("Do we have enough eggs for breakfast", "ham"),
        ("I'll order pizza for tonight", "ham"),
        ("The leftovers are in the fridge help yourself", "ham"),
        ("Shall I bring anything to the potluck", "ham"),
        ("The farmers market is open tomorrow morning", "ham"),

        # Travel / Commute
        ("The bus is running 10 minutes late today", "ham"),
        ("Traffic is heavy on the highway take the back road", "ham"),
        ("I booked the hotel for our vacation", "ham"),
        ("The flight has been delayed by two hours", "ham"),
        ("Remember to bring your passport to the airport", "ham"),
        ("I'll be arriving at the station at 5 pm", "ham"),
        ("The taxi is on its way should be there in 10 minutes", "ham"),
        ("Gas prices went up again this week", "ham"),
        ("I parked the car in the east lot", "ham"),
        ("The train schedule changed check the new times", "ham"),

        # Weather / News
        ("It might rain tomorrow bring an umbrella", "ham"),
        ("The weather is perfect for a picnic today", "ham"),
        ("Bundle up it's going to be freezing tonight", "ham"),
        ("Did you see the news about the local festival", "ham"),
        ("There's a severe weather warning for this evening", "ham"),

        # Entertainment / Hobbies
        ("Have you read that new book everyone's talking about", "ham"),
        ("The new season of our favorite show starts tonight", "ham"),
        ("I started learning guitar last week", "ham"),
        ("Let's go to the art exhibition this weekend", "ham"),
        ("I finished painting the living room it looks great", "ham"),
        ("The community garden has space for new members", "ham"),
        ("Want to go for a bike ride after work", "ham"),
        ("I signed up for a photography class", "ham"),
        ("The local team won the championship last night", "ham"),
        ("I downloaded some new songs for our playlist", "ham"),

        # Miscellaneous
        ("Remember to set the alarm for tomorrow morning", "ham"),
        ("I changed the password for our streaming account", "ham"),
        ("The neighbors invited us over for dinner", "ham"),
        ("Can you drop off the dry cleaning on your way", "ham"),
        ("I found your missing charger in the living room", "ham"),
        ("The lawn needs to be mowed this weekend", "ham"),
        ("I spoke to the mechanic about the car noise", "ham"),
        ("The washing machine is making a strange sound", "ham"),
        ("We should start packing for the move next month", "ham"),
        ("I renewed the magazine subscription for another year", "ham"),
    ]
